# Generated by Django 3.1.5 on 2022-02-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsense', '0002_auto_20220223_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pst_id',
            field=models.IntegerField(default=97),
        ),
    ]
