# Generated by Django 3.1.5 on 2022-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsense', '0003_auto_20220223_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedOption',
            field=models.CharField(default='d', max_length=2),
        ),
    ]
