# Generated by Django 3.1.5 on 2022-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsense', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='_user_likes_+', to='nonsense.Love'),
        ),
    ]
