# Generated by Django 3.1.5 on 2022-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsense', '0007_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userlikes',
            field=models.ManyToManyField(blank=True, related_name='_post_userlikes_+', to='nonsense.Love'),
        ),
    ]
