# Generated by Django 4.1.4 on 2022-12-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonsense', '0009_alter_comment_id_alter_flag_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='nonsense.post'),
        ),
    ]
